/**
 * AUTO-GENERATED by scripts/gen-image-variants.mjs — do not edit by hand.
 * Run `npm run images` after adding or replacing anything in public/images.
 */
export interface ImageMeta {
  /** intrinsic width of the source file */
  w: number;
  /** intrinsic height of the source file */
  h: number;
  /** widths available as pre-generated variants */
  v: number[];
}

export const imageMeta: Record<string, ImageMeta> = {
  "about-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "about-story.webp": {
    "w": 1086,
    "h": 1448,
    "v": [
      96,
      400,
      800
    ]
  },
  "careers-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "careers-team.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "case-community-outreach.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "case-corporate-health.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "case-equipment-installation.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "case-hospital-transformation.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "case-partnership.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "consulting-fieldwork.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "consulting-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "corporate-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "corporate-wellness.webp": {
    "w": 1122,
    "h": 1402,
    "v": [
      96,
      400,
      800
    ]
  },
  "facility-logos/finnih-medical-centre.webp": {
    "w": 1000,
    "h": 882,
    "v": [
      96,
      400,
      800
    ]
  },
  "facility-logos/kindred-path-fertility-centre.webp": {
    "w": 656,
    "h": 1000,
    "v": [
      96,
      400
    ]
  },
  "facility-logos/lifecentre-med-support.webp": {
    "w": 1000,
    "h": 714,
    "v": [
      96,
      400,
      800
    ]
  },
  "facility-logos/lifecentre-medical-services.webp": {
    "w": 1000,
    "h": 256,
    "v": [
      96,
      400,
      800
    ]
  },
  "facility-logos/sky-high-medical-centre.webp": {
    "w": 1000,
    "h": 239,
    "v": [
      96,
      400,
      800
    ]
  },
  "facility-logos/zendale-endoscopy-centre.webp": {
    "w": 1000,
    "h": 718,
    "v": [
      96,
      400,
      800
    ]
  },
  "home-hero-texture.webp": {
    "w": 1536,
    "h": 1024,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "home-who-we-are.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "how-we-work-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "how-we-work-support.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "medtech-biomedical-engineer.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "medtech-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-endoscopy.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-finnih.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-kindredpath.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-lifecentre.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-medsupport.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-skyhigh-icu.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-skyhigh.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "network-vhelar.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "partnerships-hero.webp": {
    "w": 1448,
    "h": 1086,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "partnerships-network.webp": {
    "w": 1586,
    "h": 992,
    "v": [
      96,
      400,
      800,
      1200
    ]
  },
  "zendale-logo.webp": {
    "w": 535,
    "h": 559,
    "v": [
      96,
      400
    ]
  },
  "zendale-social-card.png": {
    "w": 1200,
    "h": 630,
    "v": [
      96,
      400,
      800
    ]
  }
};

/** Builds a srcset string for a file in /public/images, or "" if none exists. */
export function srcSetFor(file: string): string {
  const entry = imageMeta[file];
  if (!entry || entry.v.length === 0) return "";
  const stem = file.replace(/\.(webp|png|jpe?g)$/i, "");
  const ext = file.slice(stem.length);
  const parts = entry.v.map((w) => `/images/${stem}-${w}.webp ${w}w`);
  parts.push(`/images/${stem}${ext} ${entry.w}w`);
  return parts.join(", ");
}
